### ISSUE TITLE
Still alive?

### ISSUE THREAD

**Issue by dmitriynosenko** [phoenixwebgroup/DotNetMongoMigrations#11]
Hi. This project is still alive or not? Will it use MongoDB new driver (2.0)?

**Comment by g0t4** [comment]
I'm in the process of considering updating a few different libraries for
the 2.0 driver, keep an eye out for updates.

**Comment by dmitriynosenko** [comment]
I like MongoMigrations, so I want to make sure that it will use the latest driver.

**Comment by g0t4** [comment]
All in good time, I'm groking the changes as they are rather substantial in
terms of the interfaces but not the functionality
