### ISSUE TITLE
Will you update library to use latest mongodb c# driver?

### ISSUE THREAD

**Issue by dmitriynosenko** [phoenixwebgroup/DotNetMongoMigrations#13]
Hi. Do you plan to update your library to use latest mongodb c# driver?
And when you plan to do this?

**Comment by g0t4** [comment]
I'm not maintaining this project anymore, do you want to take over?

**Comment by artemnf** [comment]
Hi. Update for mongodb C# driver 2.x is definitely needed as, they do not sign the driver any more, so we cannot use binding redirect. Update should be easy, they the driver is backwards compatible (except signing part). If you do not maintain this project anymore, I could take over. There is an interest in it but sticking to 1.9 version of mongodb C# driver is a real blocker.
