### ISSUE TITLE
Nuget package

### ISSUE THREAD

**Issue by dmitriynosenko** [phoenixwebgroup/DotNetMongoMigrations#16]
Hi. First of all I must thank you that you authored this project and will update it soon.
How soon you plan to update nuget package with new version?

**Comment by g0t4** [comment]
I'm on vacation, I can publish this when I get back.

**Comment by g0t4** [comment]
In the interim the old version can work from a separate project for
migrations referencing the 1.9 driver

**Comment by shatl** [comment]
+1, please release new package

**Comment by nparrish** [comment]
+1

**Comment by cd21h** [comment]
Hi @g0t4 ,
did you had a chance to look into this?

**Comment by g0t4** [comment]
Done!

**Comment by cd21h** [comment]
Thanks a lot!
