### ISSUE TITLE
Need Inteface Example

### ISSUE THREAD

**Issue by khanzzirfan** [phoenixwebgroup/DotNetMongoMigrations#21]
Hi I  really like the concept of this library and want to implement in my project.

Could you provide me a example way of implementing this library?
Thanks.

**Comment by g0t4** [comment]
There are examples in the README.markdown

**Comment by khanzzirfan** [comment]
Yes, I saw those example examples. But I was looking for complete visual studio solution to check to see how this is actually implemented at higher level.

**Comment by g0t4** [comment]
If you set one up, let me know and I can link to it, but there's nothing at this time.
